<?php
/////////////////////////////////////////////////////////////////
defined( '_V' ) or die( 'Restricted access' );
/////////////////////////////////////////////////////////////////
$lang=array(
		'Create new'=>'Izveidot jaunu'
		,'not found'=>'404 - Lapa nav atrasta'
		,'email'=>'E-pasts'
		,'password'=>'Parole'
		,'login'=>'Ieiet'
		,'logout'=>'Iziet'
		,'wrong email or pass'=>'Nepareizs e-pasts vai parole'
		,'name'=>'Nosaukums'
		,'site_name'=>'Adminka'
		,'Can type now'=>'Ievadi <strong>now</strong>, ja vēlies tagadējo laiku'
		,'value of'=>'vērtība laukā'
		,'updated'=>'tika atjaunota'
		,'friend_url'=>'url - parametrs'
			,'Shown in address bar'=>'Rādās pārluka adreses vietā'
		,'category'=>'Kategorija'
		,'published'=>'Publisks'
		,'Save'=>'Saglabāt'
		,'Submit'=>'Apstiprināt'
		,'Reorder'=>'Mainīt secību'


		,'type'=>'Tips'
		,'ordering'=>'Secība'
		,'delete'=>'Dzēst'
		,'modified'=>'Atjaunota'
		,'parent_id'=>'Apakšsadaļa'
		,'component'=>'Navigācijas rādīšanas tips'
			,'self'=>'Paskaidrojums'
			,'text'=>'Teksta sadaļa'
			,'design'=>'Dizaina sadaļa - atstāt bez izmaiņam'
			,'ajax'=>'ajax pieprasījumi'
		,'template'=>'Izskats'
			,'main'=>'Pamata'
		,'description'=>'Paskaidrojums'

		,'h'=>'Paslēpts'
		,'m'=>'Galvenā'
		,'f'=>'Apakšā'
		,'r'=>'Reģistrētiem'

		,'Edit'=>'Labot'
		,'translate'=>'Tulkošana'
		,'Translated '=>'Iztulkots'
		,'web_name'=>'Lapas teksts'
		,'No'=>'Nav'
		,'Yes'=>'Ir'
		,'menu'=>'Navigācija'
		,'lng'=>'Ieliktņi'
		,'Show original'=>'Atvērt oriģinālo'
		,'intro'=>'Ievadteksts'
		,'full'=>'Pilns teksts'
		,'Translated'=>'Iztulkots'

                , 'file choose'=>'Izvēlēties datni'
                , 'contacts'=>'Kontakti'
                , 'product'=>'Produkti'
                , 'creater'=>'Izstrādātāji'
                , 'price'=>'Cena'
                , 'specification'=>'Specifikācija'
                , 'img'=>'Bilde'
                , 'image'=>'Bildes'
                , 'images'=>'Bildes'

                , 'futures'=>'Priekšrocības'
                , 'teh_params'=>'Spec. īpašības'
                , 'variable'=>'Iespējāmās vērtības'
                , 'option'=>'Izvēlne'
                , 'multiple'=>'Saraksts'
);